### ISSUE TITLE
support mobile

### ISSUE THREAD

**Issue by jossef** [jossef/open-accessability#4]
currently it's disabled on purpose 
the goal is to support it on mobile as well

**Comment by boynet** [comment]
any info what wrong with mobile? only ui issues?

**Comment by jossef** [comment]
@ori19939 - ?

**Comment by ori19939** [comment]
fixed. will upload in few days.

**Comment by boynet** [comment]
pinged

**Comment by jossef** [comment]
@ori19939 , ETA?
